### Extension name (VScode): REST Client (with lightblue icon)
###
GET http://localhost:3000/

###
POST http://localhost:3000/api/
Content-Type: application/json

{
    "name": "David",
    "location": "10 hello world street"
}